apiVersion: v3.0.1 # Standard version (follows semantic versioning)
kind: DataContract
id: 53581432-6c55-4ba2-a65f-72344a91553a
version: 3.3.0 # Version (follows semantic versioning)
status: draft
description: # (optional)
  purpose: Views built on top of the seller tables. # (optional)
  limitations: null # (optional)
  usage: null # (optional)
tags: ['PII'] # (optional)

schema:
  - name: TEST_INVOICES
    physicalName: default/custom/1752745105/TEST_DB/TEST_SCHEMA/TEST_INVOICES
    connection_name: custom/mock-dev
    physicalType: table
    description: Provides core payment metrics 
    properties:
      - name: Confirmed Delivery Time
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public
        description: Reference date for transaction
      - name: Customer Name
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
        
  - name: trades_raw
    physicalName: default/bigquery/1763362279/dbge-4839201756/trading_ds/trades_raw
    connection_name: bigquery/bigquery-datacontract-conn
    physicalType: table
    description: Provides core payment metrics # (optional)
    tags: [ 'PII' ] # (optional)
    properties:
      - name: trade_id
        physicalType: numeric
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: trade_timestamp
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: instrument
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: side
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: qty
        physicalType: numeric
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: price
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: venue
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: execute_party
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: metadata
        physicalType: record
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: metadata.source
        physicalType: string
        primaryKey: false
        required: true
      - name: metadata.ingestion_ts
        physicalType: timestamp
        primaryKey: false
        required: true
        
  - name: data_access_test
    physicalName: default/bigquery/1763362279/dbge-4839201756/dataset_access_test/data_access_test
    connection_name: bigquery/bigquery-datacontract-conn
    physicalType: table
    description: Provides core payment metrics # (optional)
    tags: [ 'PII' ]
    properties:
      - name: name
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: email
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: phone_number
        physicalType: numeric
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: address
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: ssn
        physicalType: numeric
        primaryKey: true
        required: true
        unique: true
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: credit_card
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: age
        physicalType: numeric
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: department
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
      - name: employee_id
        physicalType: string
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ]  
      
  - name: email_events
    physicalName: default/bigquery/1751545061/sturdy-tuner-464808-c6/sales_demo/email_events
    connection_name: bigquery/development
    physicalType: table
    description: Provides core payment metrics # (optional)
    tags: [ 'PII' ] # (optional)
    properties:
      - name: eventid
        physicalType: numeric
        primaryKey: false
        required: true
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
        quality:
        - name: unique_eventid
          type: unique
          description: Event ID must be unique
          dimension: completeness
          query: |
            SELECT COUNT(*) FROM ${object} WHERE ${property} IS NOT NULL
          mustBeGreaterThan: 0  # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          mustBeLessThan: 3600   # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          severity: block # block, quarantine, alert, ignore
      - name: customerid
        physicalType: string
        primaryKey: false
        required: false
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
        quality:
        - name: not_null_customerid
          type: not_null
          description: Every order must have a customer ID
          dimension: completeness
          query: |
            SELECT COUNT(*) FROM ${object} WHERE ${property} IS NOT NULL
          mustBeGreaterThan: 0  # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          mustBeLessThan: 3600   # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          severity: block # block, quarantine, alert, ignore
      - name: event_type
        physicalType: string
        primaryKey: false
        required: false
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
        quality:
        - name: valid_event_type
          type: valid_type
          description: Event type must be valid
          dimension: completeness
          query: |
            SELECT COUNT(*) FROM ${object} WHERE ${property} IS NOT NULL
          mustBeGreaterThan: 0  # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          mustBeLessThan: 3600   # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          severity: block # block, quarantine, alert, ignore
      - name: event_date
        physicalType: date
        primaryKey: false
        required: false
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
        quality:
        - name: valid_event_date
          type: valid_date
          description: Event date must be valid
          dimension: completeness
          query: |
            SELECT COUNT(*) FROM ${object} WHERE ${property} IS NOT NULL
          mustBeGreaterThan: 0  # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          mustBeLessThan: 3600   # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          severity: block # block, quarantine, alert, ignore
      - name: email_subject
        physicalType: string
        primaryKey: false
        required: false
        unique: false
        classification: public # (optional)
        description: Reference date for transaction # (optional)
        tags: [ 'PII' ] # (optional)
        quality:
        - name: valid_email_subject
          type: short
          description: Email Subject must be valid and short
          dimension: completeness
          query: |
            SELECT COUNT(*) FROM ${object} WHERE ${property} IS NOT NULL
          mustBeGreaterThan: 0  # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          mustBeLessThan: 3600   # See supported operators here: https://bitol-io.github.io/open-data-contract-standard/v3.0.2/#valid-properties-for-operator
          severity: block # block, quarantine, alert, ignore
        # Table Quality
    quality:
    - name: rowCount
      type: sql
      description: Ensure row count is within expected volume range
      dimension: completeness
      query: |
        SELECT COUNT(*) FROM ${object}
      mustBeGreaterThan: 10
      mustBeLessThan: 10000   
      severity: alert # block, quarantine, alert, ignore

slaDefaultElement: email_events.txn_ref_dt
slaProperties:
  - property: latency # Property, see list of values in DP QoS: https://opendataproducts.org/DataQoS-as-code/#introduction
    value: 4
    unit: d # d, day, days for days; y, yr, years for years
    element: email_events.txn_ref_dt (This would not be needed as it is the same table.column as the default one)
  - property: generalAvailability
    value: "2022-05-12T09:30:10-08:00"
